// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemOdasiAPI.Data;

#nullable disable

namespace SistemOdasiAPI.Migrations
{
    [DbContext(typeof(SistemDbContext))]
    [Migration("20260716110125_EnerjiDurumuEkleme")]
    partial class EnerjiDurumuEkleme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemOdasiAPI.Models.OrtamVerisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnerjiVarMi")
                        .HasColumnType("bit");

                    b.Property<int>("Gaz")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("Nem")
                        .HasColumnType("float");

                    b.Property<double>("Sicaklik")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("OrtamVerileri");
                });
#pragma warning restore 612, 618
        }
    }
}
